// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGxhc2oIq7AbOkfD0Rt6IW4WsPfe-zm48',
    appId: '1:495227490018:web:cab505ef4a1f1dd17f98bb',
    messagingSenderId: '495227490018',
    projectId: 'newsapp-e1ff8',
    authDomain: 'newsapp-e1ff8.firebaseapp.com',
    storageBucket: 'newsapp-e1ff8.firebasestorage.app',
    measurementId: 'G-TREK0DVG97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBidiSg2uAqkn-nW_VS6YVSBzPnNUBJD44',
    appId: '1:495227490018:android:7fe68e111deef8d87f98bb',
    messagingSenderId: '495227490018',
    projectId: 'newsapp-e1ff8',
    storageBucket: 'newsapp-e1ff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxucLym7o-u3ucZUZImTyHFyrpXtosFI',
    appId: '1:495227490018:ios:7c9e4fca2a79913b7f98bb',
    messagingSenderId: '495227490018',
    projectId: 'newsapp-e1ff8',
    storageBucket: 'newsapp-e1ff8.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUxucLym7o-u3ucZUZImTyHFyrpXtosFI',
    appId: '1:495227490018:ios:7c9e4fca2a79913b7f98bb',
    messagingSenderId: '495227490018',
    projectId: 'newsapp-e1ff8',
    storageBucket: 'newsapp-e1ff8.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGxhc2oIq7AbOkfD0Rt6IW4WsPfe-zm48',
    appId: '1:495227490018:web:9cff2857a2002e057f98bb',
    messagingSenderId: '495227490018',
    projectId: 'newsapp-e1ff8',
    authDomain: 'newsapp-e1ff8.firebaseapp.com',
    storageBucket: 'newsapp-e1ff8.firebasestorage.app',
    measurementId: 'G-6K2K3JMXHQ',
  );
}
